export const EmojiGroups = [
    "smileys and people",
    "animals and nature",
    "food and drink",
    "travel and places",
    "activities",
    "objects",
    "symbols",
    "flags",
    "Running fiddle",
    "face positive",
    "face neutral",
    "face negative",
    "face role",
    "face sick",
    "creature face",
    "cat face",
    "monkey face",
    "person",
    "person role",
    "person gesture",
    "person activity",
    "family",
    "skin tone",
    "body",
    "emotion",
    "clothing",
    "animal mammal",
    "animal bird",
    "animal amphibian",
    "animal reptile",
    "animal marine",
    "animal bug",
    "plant flower",
    "plant other",
    "food fruit",
    "food vegetable",
    "food prepared",
    "food asian",
    "food sweet",
    "drink",
    "dishware",
    "travel and places",
    "activities",
    "objects",
    "symbols",
    "flags"
]